#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from sensor_msgs.msg import JointState

import numpy as np
import xml.etree.ElementTree as ET

from kuka_eki import UDPClient


def joint_state_from_xml(xml):
    root = ET.fromstring(xml)
    axes = root.find('Axis').attrib
    joint_state = JointState()
    joint_state.header.stamp = rospy.Time.now()
    joint_state.name = [
        'joint_a1',
        'joint_a2',
        'joint_a3',
        'joint_a4',
        'joint_a5',
        'joint_a6',
    ]
    joint_state.position = np.deg2rad([
        float(axes['A1']),
        float(axes['A2']),
        float(axes['A3']),
        float(axes['A4']),
        float(axes['A5']),
        float(axes['A6']),
    ])
    return joint_state


if __name__ == "__main__":
    pub = rospy.Publisher('joint_states', JointState, queue_size=10)
    conn = UDPClient(('192.168.250.16', 54602))
    conn.settimeout(0.1)
    conn.send(b'0')
    name = 'eki_state_publisher'
    rospy.init_node(name)
    while not rospy.is_shutdown():
        try:
            data = conn.recv(1024)
            joint_state = joint_state_from_xml(data)
            pub.publish(joint_state)
        except:
            pass
