#!/usr/bin/env python

import rospy
from kuka_eki import EKIDriver

from kuka_eki_msgs.srv import (
    MovePtpAxis, MovePtpAxisRequest, MovePtpAxisResponse)


class EKINode(object):

    def __init__(self, name, addr):

        self._ptp_axis_service = rospy.Service(name + '/ptp_axis', MovePtpAxis, self._ptp_axis)
        self._driver = EKIDriver(addr)
        self._driver.start()

    def _ptp_axis(self, req):
        rospy.loginfo(req)
        return MovePtpAxisResponse()


if __name__ == '__main__':

    name = 'eki_node'
    rospy.init_node(name)
    eki_node = EKINode(name, ('127.0.0.1', 49152))
    rospy.spin()
